"""Broker-truth reconciliation: turn raw MT5 deals into closed-position outcomes.

The old per-cycle reconcile was wrong three ways and overstated performance:
  1. it filtered deals by the bot's magic — but SL/TP CLOSING deals are generated by the
     broker with magic 0, so the realized PnL (which lives on the close) was dropped and the
     trade recorded as pnl=0;
  2. it only looked back 3 days, so any close during downtime was missed;
  3. it stamped every close with today's date instead of the real close time.

`aggregate_closed_positions` fixes all three: it aggregates EVERY deal by position_id (so the
broker's close deal is included), identifies the bot's positions by the magic on the OPENING
deal, and only emits a position once it is fully closed (not in the live open set). The result
mirrors MT5 exactly, so the journal — and the dashboard that reads it — show the true P&L.
"""
from __future__ import annotations

from datetime import datetime, timezone


def _num(x) -> float:
    try:
        return float(x)
    except (TypeError, ValueError):
        return 0.0


def aggregate_closed_positions(deals, open_tickets: set[int], bot_magic: int) -> list[dict]:
    """Aggregate MT5 deals into one record per CLOSED bot position.

    deals: MT5 history deals (each with position_id, type, entry, magic, profit, swap,
           commission, price, time). type 0/1 = buy/sell; entry 0 = open (carries magic),
           1+ = close. open_tickets: currently-open position tickets (still unrealized).
    Returns [{position_id, pnl, close_time(epoch), exit_price}] sorted by close_time.
    """
    by_pos: dict[int, dict] = {}
    for d in deals:
        if getattr(d, "type", None) not in (0, 1):   # skip balance/credit ops
            continue
        pid = getattr(d, "position_id", None)
        if pid is None:
            continue
        a = by_pos.setdefault(pid, {"pnl": 0.0, "magic": None, "close_time": 0, "exit": 0.0, "closed": False})
        a["pnl"] += _num(getattr(d, "profit", 0)) + _num(getattr(d, "swap", 0)) + _num(getattr(d, "commission", 0))
        entry = getattr(d, "entry", None)
        if entry == 0:                                # opening deal carries the bot's magic
            a["magic"] = getattr(d, "magic", None)
        if entry in (1, 2, 3):                        # closing / reversing deal
            a["closed"] = True
            t = int(getattr(d, "time", 0) or 0)
            if t >= a["close_time"]:
                a["close_time"] = t
                a["exit"] = _num(getattr(d, "price", 0))
    out = []
    for pid, a in by_pos.items():
        if a["magic"] != bot_magic:     # not one of our positions
            continue
        if pid in open_tickets:         # still open -> P&L not realized yet
            continue
        if not a["closed"]:             # no closing deal recorded yet
            continue
        out.append({"position_id": pid, "pnl": round(a["pnl"], 2),
                    "close_time": a["close_time"], "exit_price": a["exit"]})
    out.sort(key=lambda x: x["close_time"])
    return out


def close_iso(close_time: int) -> str:
    """Epoch seconds -> ISO8601 UTC (the real close time, not 'today')."""
    if not close_time:
        return datetime.now(timezone.utc).isoformat()
    return datetime.fromtimestamp(int(close_time), tz=timezone.utc).isoformat()
